version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
    ports:
      - "3306:3306"
    volumes:
      - ./dump-hibernate-final.sql:/docker-entrypoint-initdb.d/dump-hibernate-final.sql

  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java
    restart: always
    depends_on:
      - mysql
      - redis

